[project]
name = "habits"

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run db:migrate && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30

# Volume for storing exercise images
[[volumes]]
name = "exercise-images"
mount = "/data/images"
