[project]
name = "habits"

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run db:migrate && npm run start"
healthcheckPath = "/login"
healthcheckTimeout = 60

# Volume for storing exercise images
[[volumes]]
name = "exercise-images"
mount = "/data/images"
